#!/usr/bin/perl -w
use 5.10.1;
use warnings;
use strict;



open (IN,"paste your input here");
open (OUT,">>paste your output here");

	select (OUT);
	
	print "\'";
			
			while(<IN>){

s/\,/\\,/g;
s/\;/\\;/g;
s/\:/\\:/g;
s/\-/\\-/g;
s/\./\\./g;
s/\(/\\(/g;
s/\)/\\)/g;
s/\//\\\//g;
s/\?/\\?/g;
s/\~/\\~/g;
s/\!/\\!/g;
s/\@/\\@/g;
s/\#/\\#/g;
s/\%/\\%/g;
s/\^/\\^/g;
s/\&/\\&/g;
s/\*/\\*/g;
s/\+/\\+/g;
s/\=/\\=/g;
s/\{/\\{/g;
s/\}/\\}/g;
s/\{/\\{/g;
s/\}/\\}/g;
s/\|/\\|/g;
s/\"/\\"/g;
s/\'/\\'/g;
s/\</\\</g;
s/\>/\\>/g;
s/\[/\\[/g;
s/\]/\\]/g;
s/\`/\\`/g;

# replace the newline by ','
s/\n/\'\,\'\n/;

chomp;


print $_;
	
	}
close(IN);
close(OUT);
				
